name: Deploy to GitHub Pages subdirectory

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Prepare deployment folder
        run: |
          mkdir output
          rsync -av --exclude='.github' ./ output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_KEY }}
          external_repository: parkjin21004/parkjin21004.github.io
          publish_dir: ./output
          destination_dir: chrome_app_clone
          publish_branch: main
